name: Build and Release MiceWine RootFS

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: "Clone Repository"
        run: |
          git clone https://github.com/nitanmarcel/MiceWine-RootFS-Generator

      - name: "Environment Preparation"
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip cmake wget git p7zip build-essential pkg-config xmlto fop xsltproc llvm autoconf libxml-parser-perl bison flex glslang-tools
          pip3 install mako meson ninja docutils
          sudo ln -sf ~/.local/bin/meson /usr/bin/meson

      - name: "Setup Basic Android (x86_64) Runtime Environment"
        run: |
          git clone https://github.com/termux/termux-docker.git
          sudo cp -rf termux-docker/system/x86 /system
          sudo chown -R $(whoami):$(whoami) /system
          sudo chmod 755 -R /system

      - name: "Download Latest Release Rat Packages"
        run: |
          cd MiceWine-RootFS-Generator
          curl -LO# $(curl -s https://api.github.com/repos/KreitinnSoftware/MiceWine-RootFS-Generator/releases/latest | grep "MiceWine-Packages.zip" | grep "browser_download_url" | sed "s/\"browser_download_url\"://g" | sed "s/\"//g") || true
          unzip -o MiceWine-Packages.zip -d built-pkgs || true

      - name: "Start Building (x86_64)"
        run: |
          cd MiceWine-RootFS-Generator
          ./build-all.sh x86_64
          cd logs
          7z a /home/runner/MiceWine-RootFS-x86_64-Logs.zip

      - name: "Create RootFS File (x86_64)"
        run: |
          cd MiceWine-RootFS-Generator
          ./create-rootfs.sh x86_64
          mv "MiceWine-RootFS-($(git rev-parse --short HEAD))-x86_64.rat" /home/runner/MiceWine-RootFS-x86_64.rat

      - name: "Clean (x86_64) RootFS"
        run: |
          cd MiceWine-RootFS-Generator
          sudo rm -rf /data/data/com.micewine.emu/files/usr workdir rootfs

      - name: "Start Building (aarch64)"
        run: |
          cd MiceWine-RootFS-Generator
          ./build-all.sh aarch64
          cd logs
          7z a /home/runner/MiceWine-RootFS-aarch64-Logs.zip

      - name: "Save All Rat Packages (for next build be faster)"
        run: |
          cd MiceWine-RootFS-Generator
          cd built-pkgs
          7z a /home/runner/MiceWine-Packages.zip
          cd ..

      - name: "Create RootFS File (aarch64)"
        run: |
          cd MiceWine-RootFS-Generator
          ./create-rootfs.sh aarch64
          mv "MiceWine-RootFS-($(git rev-parse --short HEAD))-aarch64.rat" /home/runner/MiceWine-RootFS-aarch64.rat

      - name: "Get Short SHA"
        run: |
          cd MiceWine-RootFS-Generator
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: "Create Release"
        uses: softprops/action-gh-release@v2
        with:
          name: "MiceWine RootFS ${{ github.sha }}"
          tag_name: ${{ env.SHORT_SHA }}
          files: |
            /home/runner/MiceWine-RootFS-aarch64.rat
            /home/runner/MiceWine-RootFS-aarch64-Logs.zip
            /home/runner/MiceWine-Packages.zip
            /home/runner/MiceWine-RootFS-x86_64.rat
            /home/runner/MiceWine-RootFS-x86_64-Logs.zip
